# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:8.9.1
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
 #     - restore_cache:
 #         key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: change-to-api
          command: 'cd api'
      - run:
          name: install-npm
          command: 'npm install'
      - run:
          name: change-to-mobile
          command: 'cd ../mobile-app'
      - run:
          name: install-npm
          command: 'npm install'
      - run:
          name: change-to-frontend
          command: 'cd ../web-frontend'
      - run:
          name: install-npm
          command: 'npm install'
#      - save_cache:
#          key: dependency-cache-{{ checksum "package.json" }}
#          paths: 
#            - ./node_modules


